# Generated by Django 5.0.6 on 2024-08-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0002_product_delete_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
