# Generated by Django 5.0.6 on 2024-09-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0004_remove_product_created_at_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_location',
        ),
    ]
