# Generated by Django 5.0.6 on 2024-09-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0005_remove_product_custom_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('home_kitchen', 'Home & Kitchen'), ('health_beauty', 'Health & Beauty'), ('jewelry_accessories', 'Jewelry & Accessories'), ('apparel_fashion', 'Apparel & Fashion'), ('food', 'Food'), ('gadgets_computers', 'Gadgets & Computers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
