# Generated by Django 5.0.6 on 2024-10-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0010_alter_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
