# Generated by Django 5.0.6 on 2024-11-27 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0011_remove_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('home', 'Home'), ('health_beauty', 'Health & Beauty'), ('jewelry_accessories', 'Jewelry & Accessories'), ('apparel', 'Apparel'), ('bags', 'Bags'), ('footwear', 'Footwear'), ('headgear', 'Headgear'), ('food', 'Food'), ('gadgets_computers', 'Gadgets & Computers')], max_length=50),
        ),
    ]
